# -*- mode: ruby -*-
# vi: set ft=ruby :

server_ip = "192.168.42.110"

Vagrant.configure("2") do |config|
  
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.define "moel-aza" do |server|
    #BOX settings
    server.vm.box = "centos/7"

    #Provider settings
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 3072
      vb.cpus = 1
      vb.name = "moel-aza"
    end

    #Network settings
    server.vm.network "private_network", ip: server_ip
    server.vm.hostname = "moel-azaS"

    #Folder settings
    server.vm.synced_folder "./config", "/config"

    #Provision settings
    server.vm.provision "shell", privileged: false, path: "scripts/k3s_server.sh"

  end
  
end
